"""
report_generator.py — Generate downloadable PDF clinical reports.

Provides utilities to generate a complete, professional PDF report of a
patient's sepsis risk assessment using ReportLab.
"""

from __future__ import annotations

import io
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_sepsis_report(
    patient_data: Dict[str, Any],
    ml_score: float,
    lstm_score: float,
    agreement: str,
    uncertainty: float,
    retrieved_cases: List[Dict[str, Any]],
    llm_reasoning: str,
    confidence: str,
) -> io.BytesIO:
    """Generate a PDF report summarizing the sepsis analysis.

    Compiles patient vitals, model scores, similar cases, and the
    LLM's clinical reasoning into a structured PDF document.

    Parameters
    ----------
    patient_data : dict
        Patient vitals and labs (e.g., HR, Temp, MAP).
    ml_score : float
        Machine Learning risk score.
    lstm_score : float
        LSTM time-series risk score.
    agreement : str
        Model agreement classification (HIGH / MEDIUM / LOW).
    uncertainty : float
        Scalar uncertainty score.
    retrieved_cases : list of dict
        Similar cases retrieved by the RAG module.
    llm_reasoning : str
        Text generated by the LLM explaining the clinical reasoning.
    confidence : str
        Confidence score or level from the LLM.

    Returns
    -------
    io.BytesIO
        Byte stream containing the generated PDF document.
    """
    buffer = io.BytesIO()

    # Create the PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    # Define custom styles
    title_style = styles["Title"]
    title_style.fontSize = 18
    title_style.spaceAfter = 20

    heading_style = styles["Heading2"]
    heading_style.textColor = colors.HexColor("#2b6cb0")
    heading_style.spaceBefore = 15
    heading_style.spaceAfter = 10

    normal_style = styles["Normal"]
    normal_style.fontSize = 10
    normal_style.spaceAfter = 8

    story = []

    # Title
    story.append(Paragraph("AI Sepsis Risk Assessment Report", title_style))

    # Section 1: Patient Data
    story.append(Paragraph("Section 1: Patient Data", heading_style))

    # Extract required fields, default to 'N/A' if missing
    vitals_data = [
        ["Vital / Lab", "Value"],
        ["Heart Rate", f"{patient_data.get('HR', 'N/A')} bpm"],
        ["Temperature", f"{patient_data.get('Temp', 'N/A')} °C"],
        ["MAP", f"{patient_data.get('MAP', 'N/A')} mmHg"],
        ["Respiratory Rate", f"{patient_data.get('Resp', 'N/A')} breaths/min"],
        ["Lactate", f"{patient_data.get('Lactate', 'N/A')} mmol/L"],
        ["Creatinine", f"{patient_data.get('Creatinine', 'N/A')} mg/dL"],
        ["WBC", f"{patient_data.get('WBC', 'N/A')} ×10³/µL"],
    ]

    t_vitals = Table(vitals_data, colWidths=[200, 200])
    t_vitals.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor("#edf2f7")),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(t_vitals)
    story.append(Spacer(1, 10))

    # Section 2: Model Risk Scores
    story.append(Paragraph("Section 2: Model Risk Scores", heading_style))
    story.append(Paragraph(f"<b>ML Risk Score:</b> {ml_score:.2f}", normal_style))
    story.append(Paragraph(f"<b>LSTM Risk Score:</b> {lstm_score:.2f}", normal_style))
    story.append(Spacer(1, 10))

    # Section 3: Model Agreement
    story.append(Paragraph("Section 3: Model Agreement", heading_style))
    story.append(Paragraph(f"<b>Agreement Level:</b> {agreement}", normal_style))
    story.append(Paragraph(f"<b>Uncertainty Score:</b> {uncertainty:.4f}", normal_style))
    story.append(Spacer(1, 10))

    # Section 4: Similar ICU Cases
    story.append(Paragraph("Section 4: Similar ICU Cases", heading_style))
    if not retrieved_cases:
        story.append(Paragraph("No similar cases retrieved.", normal_style))
    else:
        for i, case in enumerate(retrieved_cases, 1):
            pid = case.get("patient_id", "Unknown")
            case_text = str(case.get("case", "")).replace("\n", "<br/>")
            
            story.append(Paragraph(f"<b>Case {i} (Patient ID: {pid})</b>", normal_style))
            # The case summary contains key vitals and outcome as required
            story.append(Paragraph(case_text, normal_style))
            story.append(Spacer(1, 10))

    # Section 5: AI Clinical Reasoning
    story.append(Paragraph("Section 5: AI Clinical Reasoning", heading_style))
    # Replace newlines for ReportLab paragraph rendering
    formatted_reasoning = str(llm_reasoning).replace("\n", "<br/>")
    story.append(Paragraph(f"<i>{formatted_reasoning}</i>", normal_style))
    story.append(Spacer(1, 10))

    # Section 6: Final Recommendation
    story.append(Paragraph("Section 6: Final Recommendation", heading_style))

    # Determine risk category (matching _score_to_risk_label logic from the UI)
    combined_score = max(ml_score, lstm_score)
    if combined_score >= 0.7:
        risk_label = "High Risk"
        risk_color = "red"
    elif combined_score >= 0.4:
        risk_label = "Moderate Risk"
        risk_color = "orange"
    else:
        risk_label = "Low Risk"
        risk_color = "green"

    story.append(Paragraph(
        f"<b>Recommendation:</b> <font color='{risk_color}'>{risk_label}</font>", 
        normal_style
    ))
    story.append(Paragraph(f"<b>Confidence Score:</b> {confidence}", normal_style))

    # Build the document
    doc.build(story)

    # Return the byte stream oriented at the beginning
    buffer.seek(0)
    return buffer
